<?php
/*
 * sis_import_enrollments.php
 * It's pretty simple. All this file does is import courses from EX
 * The CSV files are automagically generated by jobs on the EX Database server
 * 
 */ 

require 'functions.php';
include 'uploads_by_month.inc';

/*
 * 
 * Loop through each file we be keepin and send it on over to da Canvas peeples
 * 
 */ 

foreach ($files as $file) {

	combine_stu_fac_enrollments($file);
	$enrollments_file=$samba_share.$file.'_enrollment_combined.csv';
	if (file_fresh($enrollments_file)) {
		echo "\n\nDebug Data:\n=======================================================================================================\nFile: ".$file."\nEnrollments File: ".$enrollments_file."\n\n";
	
		// open the file real quick like so that we can grab the term_id from it... we'll need that for our batch mode process
		$importer = new CsvImporter($enrollments_file,true); 
		$data = $importer->get(2);
		// each section id in the file will start with the current term id... we're just going to use a little bit of dynamite to grab it 
		$section_id=explode('-',$data[1]['section_id']);
		$this_term=$section_id[0];
	
		// now, let's send Canvas the enrollments file for the term we're uploading	
		$url=$canvas_base_url."/api/v1/accounts/1/sis_imports.json?import_type=instructure_csv&batch_mode=true&batch_mode_term_id=sis_term_id:".$this_term;
		echo "\n\nNow uploading: ".$this_term." Enrollments\n=======================================================================================================\nURL: ".$url."\n\n";	
		system("curl -F attachment=@$enrollments_file -H 'Authorization: Bearer $access_token' '$url'");

	}

	}


?>